hooks.json
https://github.com/philipp-spiess/use-substate
=> 🍙 Add useSubstate

hooks.json
=> Chore: Update hooks

hooks.json
Apparently I pasted the non-secure link. 🙈
=> Use https://

hooks.json
add a react-hooks named dom-location
=> add dom-location hook

hooks.json
https://github.com/aiven715/promise-hook
=> Add promise-hook

hooks.json
This is a React hook that detects all or some keys from keyboard. If you want to detect few keys and execute function, you can provide a list of ASCII codes or keys in an array.
NPM: https://www.npmjs.com/package/use-key-hook
Demo: http://www.maheshhaldar.com/demo-use-key/
=> Add use-key hook in json list

hooks.json
Use indexDB as a better alternative to localStorage
=> Add useIdb

hooks.json
React hook to detect the device type. This hook is able to detect mobile, desktop, Android or iOS device.
=> Add useMobileDetect hook

hooks.json
=> add useDebounce package

hooks.json
package is renamed from use-wait to react-wait.
=> renamed package use-wait to react-wait

hooks.json
=> Add useObservable

hooks.json
https://github.com/diegohaz/constate
:)
=> Add Constate hooks

hooks.json
https://www.npmjs.com/package/use-promise
https://www.npmjs.com/package/use-call
_usePromise_:
```js
const [company] = usePromise(fetchCompanyPromise)
const [users, usersError, usersLoading] = usePromise(fetchUsersPromise)
```
_useCall_:
```js
// Sync
const defaultValues = useCall(getDefaultValues)
const three = useCall(sum, 1, 2) // fn, ...args
const companyPromise = useCall(fetchCompany, 234)
// Async
const [company] = useAsyncCall(fetchCompany, 234)
const [user, userError, userLoading] = useAsyncCall(fetchUser, 120)
```
=> Add usePromise, useCall, useAsyncCall

hooks.json
=> useMermaid hook

hooks.json
fixes https://github.com/nikgraf/react-hooks/issues/1, https://github.com/nikgraf/react-hooks/issues/2, https://github.com/nikgraf/react-hooks/issues/37
=> Big collection

site/package.json, site/src/pages/index.js, site/src/utils.js, site/yarn.lock
https://github.com/nikgraf/react-hooks/issues/4
I created fork where input syncs with URL https://stereobooster.github.io/react-hooks/?search=useTimeout. This functionality is not part of this PR, because to do it I migrated away from Gatsby
=> Highlight search terms

site/.github/ISSUE_TEMPLATE/Add_hook.md, site/.github/ISSUE_TEMPLATE/Bug_report.md
=> Issue template

hooks.json
Hello, Thanks for this project, please add this to list.
=> add useMeasure hook

hooks.json
=> Added react-motor

site/src/pages/index.js
Just read the site on my phone und realized some mobile issues on a `Hook` component (example visible in the image). This pr exists to fix those. So in concrete:
- optimizes positioning of repository reference
- adjusts font size to better fit screen resolutions
- small reorganization of jsx to work with adjusted styles
=> some mobile optimizations

hooks.json
=> Add useFetch

hooks.json
Add hooks for the Navi routing library:
- `useCurrentRoute`
- `useLoadingRoute`
- `useHistory`
=> Add Navi hooks

hooks.json
Add `useIntercom` hook to add the intercom chat bubble to your app
=> Add useIntercom hook

hooks.json
A simple react hook to encapsulate async state
=> Add useAsync

hooks.json
I added near the top to avoid a merge conflict. Just a thought, but you may want to alphabetize at some point.
=> added a bunch of hooks

hooks.json
Add `useMouseAction`, `useMouseDown` and `useMouseUp` from [`use-mouse-action`](https://github.com/dimitrinicolas/use-mouse-action)
=> Add useMouseAction, useMouseDown and useMouseUp from use-mouse-action

hooks.json
Notify when GA and GTM are loaded in your React Component
=> Add useTrackingIsLoaded Hook

.travis.yml, site/src/hooks.json.test.js
@nikgraf 
Related to https://github.com/nikgraf/react-hooks/pull/87
I think it's helpfull to find duplicated hooks automatically in the test. 
(And I added "yarn test" to `.travis.yml` script. Is it OK?)
=> Add test code to find duplicated hooks

hooks.json
https://github.com/pelotom/use-methods
=> Add use-methods

site/src/pages/index.js, site/src/utils.js
First click on the tag - add it to query.
Second click on the tag - remove it from query.
Not sure if this is something you like or not, but it felt natural
=> Toggle tags and subHooks

hooks.json
Added new [`react-use`](https://github.com/streamich/react-use) hooks.
=> New react-use hooks

hooks.json
https://www.npmjs.com/package/use-modal-hook
=> Added use modal hook 

hooks.json
Add `useFile`, `useObjectURL`, `useImageData` and `useImageFile`.
=> Add some file processing hooks

hooks.json
for working with react-leaflet maps
=> useLeaflet

hooks.json
Add `useSwipeable` from `react-swipeable`
- https://github.com/dogfessional/react-swipeable
=> add useSwipeable from react-swipeable

hooks.json
=> Add useStateSnapshots

hooks.json
=> add useSelectors hook

hooks.json
Added hooks useLeafletIsMoving & useLeafletIsZooming
=> useLeafletIsMoving & useLeafletIsZooming

hooks.json
https://github.com/craig1123/react-recipes
=> Adding react-recipes

hooks.json
useScrollData hook returns information about scroll speed, distance, direction and more. Useful when building dynamic navigation bars or doing other scroll related UI updates.
=> Add useScrollData hook

hooks.json
There were some internal file movements.
=> Update source links for rest-hooks

hooks.json
```json
{
"name": "@koale/useWorker",
"tags": [
"useworker",
"web worker",
"background",
"heavy task",
"blocking UI"
],
"repositoryUrl": "https://github.com/alewin/useWorker",
"importStatement": "import { useWorker } from '@koale/useworker'"
},
```
=> add @koale/useworker

hooks.json
=> Add @awgv/use-timer-hook

hooks.json
=> Add @lagunaisw/use-split-in-chunks

hooks.json
add useRecorder - 
An Audio Player & Microphone recorder hook for react web apps
[Demo](https://p1wmc.csb.app/)
[npm](https://www.npmjs.com/package/use-recorder)
=> add(hook): useRecorder by @orizens
